<?php

/**
 * Stub generated by xlatte
 */
class Category extends categoryBase
{
    /**
     * @remote
     * @param object $options
     * @param string $orderBy
     * @return Category
     */
    public static function searchOne($options, $orderBy = ""){

        $query = "SELECT #COLUMNS FROM category";

        $options = self::isAuthorized($options);
        $query = self::addOptions($query, $options);
        $query = self::addOrderBy($query, $orderBy);

        return DL::oneOf('Category', $query);
    }

    /**
     * @remote
     * @param object $options
     * @param string $orderBy
     * @return Category[]
     */
    public static function search($options, $orderBy = ""){

        $query = "SELECT #COLUMNS FROM category";

        $options = self::isAuthorized($options);
        $query = self::addOptions($query, $options);
        $query = self::addOrderBy($query, $orderBy);

        return DL::arrayOf('Category', $query);
    }

    /**
     * @remote
     * @param number $idcategory
     * @return Category[]
     */
    public static function categoriesInProject($idcategory)
    {
        $idporject = DL::oneOf('Category', "
			SELECT idproject 
			FROM category 
			WHERE idcategory = '$idcategory' 
		");

        $idporject = $idporject->idproject;

        return DL::arrayOf('Category', "
			SELECT #COLUMNS
			FROM category
				JOIN image USING (idcategory)
			WHERE idproject = '$idporject'
				AND category.trash = false
				AND image.trash = false
				AND image.archived = false
			GROUP BY category.name
		");
    }

    static function addOptions($query, $options){
        $size = 0;
        if($options != null) $size = count($options);
        if($size > 0) {
            $query .= " WHERE "; $i = 0;
            foreach ($options as $key => $value) {
                $query .= "$key = '$value'";$i++;
                if ($i < $size) $query .= " AND ";
            }
        }
        return $query;
    }

    static function addOrderBy($query, $orderBy){
        if($orderBy != "")
            $query .= " ORDER BY ". $orderBy;
        return $query;
    }

    static function isAuthorized($options){
        if(!isset($_SESSION['iduser'])){
            $options['archived'] = 'false';
            $options['trash'] = 'false';
        }
        return $options;
    }

}