<?php

/**
 * Stub generated by xlatte
 */
class Comment extends commentBase
{

	const USER = 1;
	const ROOT = 0;

	/**
	 * @remote
	 * @param number $idconversation
	 * @return Comment[]
	 */
	public static function byIdConversation($idconversation)
	{
		$notification = DL::oneOf('Notification', "
			SELECT #COLUMNS
			FROM notification
			WHERE idconversation = '$idconversation'
				AND viewed = false
		");

		if ($notification) {
			$user = (isset($_SESSION['iduser'])) ? self::ROOT : self::USER;
			if ($notification->user != $user) {
				$notification->viewed = true;
				$notification->save();
			}
		}

		return DL::arrayOf('Comment', "
			SELECT #COLUMNS
			FROM comment
			WHERE idconversation = '$idconversation'
		");
	}

	/**
	 * @override
	 * @return boolean
	 */
	public function onInserting()
	{
		$this->created = DL::dateTime();

		$notification = DL::oneOf('Notification', "
			SELECT #COLUMNS
			FROM notification
			WHERE idconversation = '$this->idconversation'
		");

		$user = (isset($_SESSION['iduser'])) ? self::ROOT : self::USER;

		if ($notification) {
			$notification->user = $user;
			$notification->viewed = false;
			$notification->created = DL::dateTime();
			$notification->save();

		} else if (!$notification) {
			$notification = new Notification();
			$notification->idconversation = $this->idconversation;
			$notification->user = $user;
			$notification->save();
		}

		return true;
	}
}