<?php

/**
 * Stub generated by xlatte
 */
class Conversation extends conversationBase
{

	/**
	 * @remote
	 * @param number $idowner
	 * @param string $owner
	 * @return Conversation[]
	 */
	public static function byIdOwner($idowner, $owner)
	{
		return DL::arrayOf('Conversation', "
			SELECT #COLUMNS
			FROM conversation
			WHERE idowner = '$idowner'
				AND owner = '$owner'
		");

	}
}