<?php

/**
 * Stub generated by xlatte
 */
class User extends userBase
{

    /**
     * @remote
     * @return boolean
     */
    public static function isLogin(){
        return isset($_SESSION['iduser']);
    }

    /**
     * @remote
     * @param object $options
     * @return boolean
     */
    public static function login($options){
        $users = self::search($options);

        if(count($users) > 0) {
            session_start();
            $_SESSION['iduser'] = $users[0]->iduser;
            return true;
        }
        return false;
    }

    /**
     * @remote
     * @return boolean
     */
    public static function logout(){
        $_SESSION['iduser'] = null;
        return true;
    }

    /**
     * @param object | array $options
     * @return User[]
     */
    static function search($options){

        $query = "SELECT #COLUMNS FROM user";

        $size = count($options);
        if($size > 0){
            $query .= " WHERE "; $i = 0;
            foreach($options as $key => $value){
                $query .= "$key = '$value'";$i++;
                if($i < $size) $query .= " AND ";
            }
        }

        return DL::arrayOf('User', $query);
    }
}