/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table category
	 */
	export class Category extends categoryBase{

		//region Static
		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Methods
		//endregion

		//region Events
		//endregion

		//region Properties
        /**
         * Property field
         */
        private _images: Image[] = null;

        /**
         * Gets or sets the array of images
         *
         * @returns {Image[]}
         */
        get images(): Image[] {
            return this._images;
        }

        /**
         * Gets or sets the array of images
         *
         * @param {Image[]} value
         */
        set images(value: Image[]) {
            this._images = value;
        }
		//endregion

	}
}