/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table file
	 */
	export class File extends fileBase{

		//region Static
		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}