/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table history
	 */
	export class History extends historyBase{

		//region Static
		//endregion

		//region Fields
		owner: string;
		//endregion

		//region Private Methods
		//endregion

		//region Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}