/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table notification
	 */
	export class Notification extends notificationBase{

		//region Static
		//endregion

		//region Fields
		project: string;
        idowner: number;
		owner: string;
		affair: string;
		guid: string;
		prototype: Image;
		//endregion

		//region Private Methods
		//endregion

		//region Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}