/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table project
	 */
	export class Project extends projectBase{

		//region Static
		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}