/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table user
	 */
	export class User extends userBase{

		//region Static
		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}